version: '3'

services:
  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  python-workspace:
    container_name: python-workspace
    image: python:latest
    volumes:
      - /c/projects/House_of_Wisdom/solidity/freeCodeCamp:/freeCodeCamp
    working_dir: /freeCodeCamp
    command:  bash -c "pip install -r devops_tools/requirements.txt && tail -F anything"
      



# docker network ls



