version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - /data/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    expose:
      - "9000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:


# ERROR - Max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] - https://community.sonarsource.com/t/when-installing-sonarqube-7-9-1-it-shows-me-the-following-error/14660
# FIX - https://stackoverflow.com/questions/51445846/elasticsearch-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc

# ERROR flood stage disk watermark [95%] exceeded - https://stackoverflow.com/questions/33369955/low-disk-watermark-exceeded-on
# FIX - https://community.sonarsource.com/t/sonarqube-fails-to-open-issues-page/18483 OR https://medium.com/100-days-of-linux/how-to-resize-a-linux-root-file-system-af3e5096b4e4
 

