version: "3"

services:
  sonarqube:
    image: sonarqube:8.9.1-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data_ver8:/opt/sonarqube/data
      - sonarqube_extensions_ver8:/opt/sonarqube/extensions
      - sonarqube_logs_ver8:/opt/sonarqube/logs
    ports:
      - 80:80
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - db_ver8:/var/lib/postgresql
      - db_data_ver8:/var/lib/postgresql/data

volumes:
  sonarqube_data_ver8:
  sonarqube_extensions_ver8:
  sonarqube_logs_ver8:
  db_ver8:
  db_data_ver8: