version: '3'

services:

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  python-workspace:
    container_name: python-workspace
    image: python:3.9
    volumes:
      # - [FULL_PATH_TO_WORKSPACE]:/web3_academy
      - /c/projects/House_of_Wisdom/solidity/web3_academy_test:/web3_academy
    working_dir: /web3_academy
    command:  bash -c "
          apt-get update &&
          apt-get install -y bc jq &&
          pip install web3 &&
          tail -F anything"
    