version: '3'

services:
  ganache-cli:
    container_name: ganache-cli
    image: ganache-test
    ports:
      - 8545:8545

  truffle-drizzle:
    container_name: truffle-drizzle
    image: truffledrizzle-test
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "truffle compile &&
             truffle test &&
             truffle migrate &&
             cp -R output/contracts client/src/contracts/ && 
             cd client &&
             ls -l && 
             ls -l src/contracts && 
             npm start"
    ports:
      - 3000:3000
    volumes:
      - ./truffledrizzle/client/src:/client/src
      - ./truffledrizzle/contracts:/contracts
      - ./truffledrizzle/migrations:/migrations
      - ./truffledrizzle/test:/test
      - ./truffledrizzle/truffle-config.js:/truffle-config.js
      







