global:
  scrape_interval: 15s
  evaluation_interval: 15s
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
    # whatever you want
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['promet.heus:9090']
      labels:
        alias: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
    # - targets: ['cadvisor:8080']
    - targets: ['192.168.82.147:8080']
      labels:
        alias: 'cadvisor'
  - job_name: 'node-exporter'
    static_configs:
    # - targets: ['node-exporter:9100']
    - targets: ['192.168.82.147:9100']
      labels:
        alias: 'node-exporter'