version: '3'

services:

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  python-brownie-workspace:
    container_name: python-workspace
    image: python:3.9
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/web3_academy
    volumes:
      - ${PWD}:/web3_academy
    working_dir: /web3_academy
    command:  bash -c "
          apt-get update &&
          apt-get install -y bc jq &&
          pip install web3 &&
          pip install tinyec &&
          tail -F anything"